version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-laravel-up
    volumes:
      - ./user-profile-app:/var/www/html:delegated # Sử dụng `delegated` để ưu tiên hiệu suất
    ports:
      - "8080:80"
    networks:
      - web
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - mysql
      - redis # Thêm Redis vào dependencies
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql-laravel-up
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: user-profile-app
    ports:
      - "3306:3306"
    networks:
      - web
    volumes:
      - mysql-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password' # Giảm độ trễ kết nối

  redis:
    image: redis:alpine
    container_name: redis-laravel-up
    ports:
      - "6379:6379"
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  mysql-data:
